-- MySQL Script generated by MySQL Workbench
-- 05/14/18 15:20:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sqlpoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sqlpoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sqlpoo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sqlpoo` ;

-- -----------------------------------------------------
-- Table `sqlpoo`.`esquema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sqlpoo`.`esquema` (
  `idesquema` INT NOT NULL,
  `nombre_esquema` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idesquema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sqlpoo`.`sustantivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sqlpoo`.`sustantivo` (
  `idsustantivo` INT NOT NULL,
  `nombre_sust` VARCHAR(45) NOT NULL,
  `esquema_idesquema` INT NOT NULL,
  PRIMARY KEY (`idsustantivo`),
  INDEX `fk_sustantivo_esquema1_idx` (`esquema_idesquema` ASC),
  CONSTRAINT `fk_sustantivo_esquema1`
    FOREIGN KEY (`esquema_idesquema`)
    REFERENCES `sqlpoo`.`esquema` (`idesquema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sqlpoo`.`triada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sqlpoo`.`triada` (
  `idtriada` INT NOT NULL,
  `conector` VARCHAR(45) NOT NULL,
  `sustantivo_idsustantivo` INT NOT NULL,
  `sustantivo_idsustantivo1` INT NOT NULL,
  `dependencia_triada` INT NULL,
  PRIMARY KEY (`idtriada`),
  INDEX `fk_triada_sustantivo_idx` (`sustantivo_idsustantivo` ASC),
  INDEX `fk_triada_sustantivo1_idx` (`sustantivo_idsustantivo1` ASC),
  INDEX `fk_triada_triada1_idx` (`dependencia_triada` ASC),
  CONSTRAINT `fk_triada_sustantivo`
    FOREIGN KEY (`sustantivo_idsustantivo`)
    REFERENCES `sqlpoo`.`sustantivo` (`idsustantivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triada_sustantivo1`
    FOREIGN KEY (`sustantivo_idsustantivo1`)
    REFERENCES `sqlpoo`.`sustantivo` (`idsustantivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triada_triada1`
    FOREIGN KEY (`dependencia_triada`)
    REFERENCES `sqlpoo`.`triada` (`idtriada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
